/* =====================================================
   RAIZEN V2 — DATA
   JJK-inspired fan universe data (original summaries)
   ===================================================== */

const RAIZEN_DATA = {
  version: "2.0.0",
  characters: [
    {
      id: "gojo",
      name: "Satoru Gojo",
      alias: "The Honored One",
      grade: "Special Grade",
      affiliation: "Tokyo Jujutsu High",
      role: "Teacher / Combat",
      rarity: "MYTHIC",
      baseStats: { hp: 1250, atk: 980, def: 920, spd: 950, energy: 120 },
      description: "The strongest modern sorcerer. His presence alone shifts the balance of the jujutsu world. Limitless technique paired with Six Eyes makes him nearly untouchable.",
      personality: "Playful, arrogant, protective of his students. Hides deep loneliness behind a carefree mask.",
      abilities: ["Limitless", "Six Eyes", "Blue", "Red", "Hollow Purple"],
      domain: "Unlimited Void",
      fightingStyle: "Overwhelming range control and instant neutralization",
      strengths: ["Near-invulnerability", "Massive AOE", "Speed"],
      limitations: ["High energy cost for domain", "Mental burden of Six Eyes"],
      trivia: "Often called the strongest by both allies and enemies.",
      relationships: ["Yuji (student)", "Geto (former best friend)", "Shoko (colleague)"],
      story: ["Hidden Inventory", "Shibuya Incident", "Shinjuku Showdown"],
      skills: {
        basic: { name: "Cursed Strike", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Blue", power: 1.6, energy: 25, type: "technique", effect: "pull" },
        skill2: { name: "Red", power: 1.8, energy: 30, type: "technique", effect: "knockback" },
        ultimate: { name: "Hollow Purple", power: 3.2, energy: 60, type: "ultimate", effect: "pierce" },
        defense: { name: "Infinity", power: 0, energy: 15, type: "guard", effect: "block" }
      }
    },
    {
      id: "yuji",
      name: "Yuji Itadori",
      alias: "Vessel of Sukuna",
      grade: "Grade 1",
      affiliation: "Tokyo Jujutsu High",
      role: "Fighter",
      rarity: "LEGENDARY",
      baseStats: { hp: 1100, atk: 1050, def: 780, spd: 880, energy: 100 },
      description: "A high schooler who swallowed a cursed object and became the vessel of the King of Curses. Exceptional physical prowess and relentless will.",
      personality: "Kind-hearted, stubborn, values life deeply. Refuses to abandon anyone.",
      abilities: ["Divergent Fist", "Black Flash", "Blood Manipulation (partial)"],
      domain: null,
      fightingStyle: "Close-range explosive combos and Black Flash timing",
      strengths: ["High ATK", "Combo potential", "Resilience"],
      limitations: ["No innate domain yet", "Sukuna risk"],
      trivia: "Can land Black Flash with unnatural consistency.",
      relationships: ["Megumi", "Nobara", "Gojo", "Choso"],
      story: ["Introduction", "Vs Mahito", "Shibuya", "Culling Game"],
      skills: {
        basic: { name: "Divergent Fist", power: 1.1, energy: 0, type: "physical" },
        skill1: { name: "Black Flash", power: 2.0, energy: 20, type: "technique", effect: "crit" },
        skill2: { name: "Manji Kick", power: 1.5, energy: 15, type: "physical" },
        ultimate: { name: "Sukuna's Resonance", power: 2.8, energy: 55, type: "ultimate", effect: "burst" },
        defense: { name: "Iron Will", power: 0, energy: 10, type: "guard" }
      }
    },
    {
      id: "megumi",
      name: "Megumi Fushiguro",
      alias: "Ten Shadows Heir",
      grade: "Grade 1",
      affiliation: "Tokyo Jujutsu High",
      role: "Summoner / Strategist",
      rarity: "LEGENDARY",
      baseStats: { hp: 980, atk: 820, def: 850, spd: 900, energy: 110 },
      description: "Inherited the Ten Shadows Technique. Calm, analytical, and willing to sacrifice himself for others. Potential to rival even Gojo.",
      personality: "Serious, reserved, deeply loyal. Struggles with self-worth.",
      abilities: ["Ten Shadows", "Divine Dogs", "Nue", "Mahoraga (potential)"],
      domain: "Chimera Shadow Garden",
      fightingStyle: "Shikigami coordination and adaptive strategy",
      strengths: ["Versatility", "Summon control", "Domain potential"],
      limitations: ["Shikigami vulnerability", "High skill ceiling"],
      trivia: "Can use multiple shadows simultaneously with enough mastery.",
      relationships: ["Yuji", "Tsumiki", "Gojo", "Toji"],
      story: ["Introduction", "Hidden Inventory", "Shibuya", "Culling Game"],
      skills: {
        basic: { name: "Shadow Strike", power: 0.9, energy: 0, type: "physical" },
        skill1: { name: "Divine Dogs", power: 1.4, energy: 20, type: "summon", effect: "multi" },
        skill2: { name: "Nue", power: 1.7, energy: 25, type: "summon", effect: "lightning" },
        ultimate: { name: "Mahoraga Potential", power: 2.9, energy: 65, type: "ultimate", effect: "adapt" },
        defense: { name: "Shadow Shield", power: 0, energy: 15, type: "guard" }
      }
    },
    {
      id: "nobara",
      name: "Nobara Kugisaki",
      alias: "Straw Doll Sorcerer",
      grade: "Grade 1",
      affiliation: "Tokyo Jujutsu High",
      role: "Ranged / Support",
      rarity: "EPIC",
      baseStats: { hp: 920, atk: 880, def: 720, spd: 860, energy: 95 },
      description: "Confident and stylish. Uses Straw Doll Technique to attack from distance and punish cursed energy links.",
      personality: "Bold, fashionable, unapologetic. Values her own life and others equally.",
      abilities: ["Straw Doll", "Resonance", "Hairpin"],
      domain: null,
      fightingStyle: "Long-range resonance and precise cursed tool strikes",
      strengths: ["Ranged damage", "Link attacks"],
      limitations: ["Fragile up close", "Tool dependency"],
      trivia: "Never backs down from a fight or an argument about style.",
      relationships: ["Yuji", "Megumi", "Maki"],
      story: ["Introduction", "Kyoto Event", "Shibuya"],
      skills: {
        basic: { name: "Hammer Strike", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Resonance", power: 1.6, energy: 22, type: "technique", effect: "link" },
        skill2: { name: "Hairpin", power: 1.9, energy: 28, type: "technique", effect: "explode" },
        ultimate: { name: "Soul Resonance", power: 2.5, energy: 50, type: "ultimate" },
        defense: { name: "Straw Guard", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "nanami",
      name: "Kento Nanami",
      alias: "The Salaryman Sorcerer",
      grade: "Grade 1",
      affiliation: "Tokyo Jujutsu High",
      role: "Tank / Crit",
      rarity: "EPIC",
      baseStats: { hp: 1080, atk: 940, def: 900, spd: 780, energy: 90 },
      description: "Former salaryman turned sorcerer. Ratio Technique allows precise weak-point exploitation. Reliable and professional.",
      personality: "Calm, logical, exhausted by overtime. Deeply cares for juniors.",
      abilities: ["Ratio Technique", "Collapse"],
      domain: null,
      fightingStyle: "Precise critical strikes on 7:3 ratios",
      strengths: ["Critical hits", "Consistency"],
      limitations: ["Predictable patterns", "Overtime fatigue"],
      trivia: "Considers overtime the true curse.",
      relationships: ["Yuji", "Gojo", "Haibara"],
      story: ["Vs Mahito", "Shibuya"],
      skills: {
        basic: { name: "Blunt Strike", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Ratio Slash", power: 1.7, energy: 20, type: "technique", effect: "crit" },
        skill2: { name: "Collapse", power: 1.5, energy: 18, type: "technique" },
        ultimate: { name: "Overtime Critical", power: 2.6, energy: 45, type: "ultimate", effect: "crit" },
        defense: { name: "Professional Guard", power: 0, energy: 10, type: "guard" }
      }
    },
    {
      id: "yuta",
      name: "Yuta Okkotsu",
      alias: "Special Grade Prodigy",
      grade: "Special Grade",
      affiliation: "Tokyo Jujutsu High",
      role: "Hybrid Fighter",
      rarity: "MYTHIC",
      baseStats: { hp: 1150, atk: 960, def: 880, spd: 920, energy: 130 },
      description: "Once haunted by Rika, now a special grade with immense cursed energy and Copy technique potential.",
      personality: "Kind, awkward, fiercely protective. Grows into quiet confidence.",
      abilities: ["Copy", "Rika", "Reverse Cursed Technique"],
      domain: "Authentic Mutual Love",
      fightingStyle: "Adaptive technique copy and overwhelming energy",
      strengths: ["Versatility", "Healing", "Raw power"],
      limitations: ["Emotional triggers", "Energy management"],
      trivia: "One of the few to fully control a special grade spirit.",
      relationships: ["Maki", "Gojo", "Rika"],
      story: ["JJK 0", "Culling Game", "Shinjuku"],
      skills: {
        basic: { name: "Cursed Energy Blast", power: 1.1, energy: 0, type: "technique" },
        skill1: { name: "Rika Assist", power: 1.8, energy: 25, type: "summon" },
        skill2: { name: "Copy Strike", power: 1.6, energy: 22, type: "technique" },
        ultimate: { name: "Pure Love Beam", power: 3.0, energy: 60, type: "ultimate" },
        defense: { name: "RCT Barrier", power: 0, energy: 20, type: "guard", effect: "heal" }
      }
    },
    {
      id: "maki",
      name: "Maki Zenin",
      alias: "Heavenly Restriction",
      grade: "Special Grade (potential)",
      affiliation: "Tokyo Jujutsu High / Zenin",
      role: "Physical Fighter",
      rarity: "LEGENDARY",
      baseStats: { hp: 1050, atk: 1100, def: 950, spd: 980, energy: 40 },
      description: "Born with Heavenly Restriction. No cursed energy but superhuman physical ability after fully embracing her path.",
      personality: "Blunt, determined, free from clan constraints. Seeks true strength.",
      abilities: ["Heavenly Restriction", "Cursed Tool Mastery"],
      domain: null,
      fightingStyle: "Pure physical combat and weapon mastery",
      strengths: ["Speed", "Power", "No CE detection"],
      limitations: ["No cursed techniques", "Tool reliance"],
      trivia: "Became a true monster after discarding everything.",
      relationships: ["Mai", "Yuta", "Toji"],
      story: ["Kyoto Event", "Perfect Preparation", "Culling Game"],
      skills: {
        basic: { name: "Weapon Slash", power: 1.2, energy: 0, type: "physical" },
        skill1: { name: "Flash Step", power: 1.5, energy: 5, type: "physical", effect: "speed" },
        skill2: { name: "Soul Split", power: 1.9, energy: 8, type: "physical" },
        ultimate: { name: "Zero CE Assault", power: 2.7, energy: 15, type: "ultimate" },
        defense: { name: "Evasion", power: 0, energy: 5, type: "guard" }
      }
    },
    {
      id: "todo",
      name: "Aoi Todo",
      alias: "Boogie Woogie",
      grade: "Grade 1",
      affiliation: "Kyoto Jujutsu High",
      role: "Disruptor",
      rarity: "EPIC",
      baseStats: { hp: 1120, atk: 990, def: 860, spd: 870, energy: 100 },
      description: "Obsessed with brotherhood and Takada-chan. Boogie Woogie swaps positions with a clap, creating chaos.",
      personality: "Loud, passionate, surprisingly insightful about people.",
      abilities: ["Boogie Woogie"],
      domain: null,
      fightingStyle: "Positional warfare and sudden swaps",
      strengths: ["Disruption", "Team synergy"],
      limitations: ["Predictable after repeated use"],
      trivia: "Judges people by their taste in women.",
      relationships: ["Yuji (brother)", "Mai"],
      story: ["Kyoto Event", "Shibuya"],
      skills: {
        basic: { name: "Heavy Punch", power: 1.1, energy: 0, type: "physical" },
        skill1: { name: "Boogie Woogie", power: 0.8, energy: 15, type: "technique", effect: "swap" },
        skill2: { name: "Brother Combo", power: 1.7, energy: 20, type: "physical" },
        ultimate: { name: "True Brotherhood", power: 2.4, energy: 45, type: "ultimate" },
        defense: { name: "Clap Guard", power: 0, energy: 10, type: "guard" }
      }
    },
    {
      id: "sukuna",
      name: "Ryomen Sukuna",
      alias: "King of Curses",
      grade: "Special Grade",
      affiliation: "Independent",
      role: "Destroyer",
      rarity: "MYTHIC",
      baseStats: { hp: 1400, atk: 1300, def: 1000, spd: 940, energy: 150 },
      description: "The undisputed King of Curses from a thousand years ago. Malevolent, powerful, and utterly dominant.",
      personality: "Arrogant, cruel, enjoys battle and destruction. Values only strength.",
      abilities: ["Dismantle", "Cleave", "Fire Arrow", "Malevolent Shrine"],
      domain: "Malevolent Shrine",
      fightingStyle: "Absolute offense and domain supremacy",
      strengths: ["Highest damage", "Domain open", "Versatility"],
      limitations: ["Vessel limitations", "Arrogance"],
      trivia: "His fingers are the strongest cursed objects.",
      relationships: ["Yuji (vessel)", "Uraume"],
      story: ["Introduction", "Shibuya", "Shinjuku Showdown"],
      skills: {
        basic: { name: "Dismantle", power: 1.3, energy: 0, type: "technique" },
        skill1: { name: "Cleave", power: 1.9, energy: 25, type: "technique", effect: "slash" },
        skill2: { name: "Fire Arrow", power: 2.1, energy: 30, type: "technique", effect: "burn" },
        ultimate: { name: "Malevolent Shrine", power: 3.5, energy: 70, type: "ultimate", effect: "domain" },
        defense: { name: "Cursed Armor", power: 0, energy: 15, type: "guard" }
      }
    },
    {
      id: "geto",
      name: "Suguru Geto",
      alias: "Curse User Leader",
      grade: "Special Grade",
      affiliation: "Curse Users",
      role: "Manipulator",
      rarity: "LEGENDARY",
      baseStats: { hp: 1080, atk: 900, def: 870, spd: 850, energy: 125 },
      description: "Former star student who fell into ideology. Commands cursed spirits with absolute control.",
      personality: "Charismatic, ideologically driven, tragic.",
      abilities: ["Cursed Spirit Manipulation", "Maximum: Uzumaki"],
      domain: null,
      fightingStyle: "Army of spirits and overwhelming numbers",
      strengths: ["Numbers", "Versatility"],
      limitations: ["Spirit quality dependence"],
      trivia: "Once the strongest alongside Gojo.",
      relationships: ["Gojo", "Shoko", "Kenjaku"],
      story: ["JJK 0", "Hidden Inventory"],
      skills: {
        basic: { name: "Spirit Strike", power: 1.0, energy: 0, type: "summon" },
        skill1: { name: "Spirit Swarm", power: 1.5, energy: 20, type: "summon", effect: "multi" },
        skill2: { name: "Uzumaki Charge", power: 1.8, energy: 30, type: "technique" },
        ultimate: { name: "Maximum Uzumaki", power: 2.9, energy: 55, type: "ultimate" },
        defense: { name: "Spirit Shield", power: 0, energy: 15, type: "guard" }
      }
    },
    {
      id: "mahito",
      name: "Mahito",
      alias: "Idle Transfiguration",
      grade: "Special Grade",
      affiliation: "Disaster Curses",
      role: "Soul Manipulator",
      rarity: "LEGENDARY",
      baseStats: { hp: 1000, atk: 920, def: 800, spd: 910, energy: 115 },
      description: "A disaster curse born from human hatred of other humans. Toys with souls and forms.",
      personality: "Playful, sadistic, curious about the soul.",
      abilities: ["Idle Transfiguration", "Body Repel"],
      domain: "Self-Embodiment of Perfection",
      fightingStyle: "Soul damage and shape-shifting",
      strengths: ["Soul attacks", "Regeneration"],
      limitations: ["Black Flash vulnerability"],
      trivia: "Grows stronger by understanding the soul.",
      relationships: ["Jogo", "Hanami", "Geto/Kenjaku"],
      story: ["Vs Mahito", "Shibuya"],
      skills: {
        basic: { name: "Soul Punch", power: 1.1, energy: 0, type: "technique" },
        skill1: { name: "Transfigure", power: 1.6, energy: 22, type: "technique", effect: "deform" },
        skill2: { name: "Body Repel", power: 1.4, energy: 18, type: "technique" },
        ultimate: { name: "Self-Embodiment", power: 2.8, energy: 60, type: "ultimate", effect: "domain" },
        defense: { name: "Soul Harden", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "choso",
      name: "Choso",
      alias: "Blood Brothers",
      grade: "Special Grade",
      affiliation: "Death Paintings",
      role: "Blood Controller",
      rarity: "EPIC",
      baseStats: { hp: 1060, atk: 910, def: 880, spd: 820, energy: 105 },
      description: "Eldest of the Death Painting Wombs. Sees Yuji as a brother after awakening.",
      personality: "Calm, protective of family, surprisingly gentle.",
      abilities: ["Blood Manipulation", "Convergence", "Supernova"],
      domain: null,
      fightingStyle: "Blood projectiles and close-range blood weapons",
      strengths: ["Sustained damage", "Control"],
      limitations: ["Blood volume"],
      trivia: "Protects his brothers above all else.",
      relationships: ["Yuji", "Eso", "Kechizu"],
      story: ["Death Painting", "Shibuya", "Culling Game"],
      skills: {
        basic: { name: "Blood Slash", power: 1.0, energy: 0, type: "technique" },
        skill1: { name: "Piercing Blood", power: 1.7, energy: 20, type: "technique" },
        skill2: { name: "Supernova", power: 1.9, energy: 28, type: "technique", effect: "aoe" },
        ultimate: { name: "Blood Flow", power: 2.5, energy: 50, type: "ultimate" },
        defense: { name: "Blood Armor", power: 0, energy: 15, type: "guard" }
      }
    },
    {
      id: "toji",
      name: "Toji Fushiguro",
      alias: "The Sorcerer Killer",
      grade: "Special Grade (potential)",
      affiliation: "Independent",
      role: "Assassin",
      rarity: "MYTHIC",
      baseStats: { hp: 1180, atk: 1200, def: 980, spd: 1050, energy: 20 },
      description: "Heavenly Restriction user who became the ultimate assassin against sorcerers. No cursed energy, pure physical terror.",
      personality: "Mercenary, cold, surprisingly soft toward family in rare moments.",
      abilities: ["Heavenly Restriction", "Inventory Curse", "Cursed Tools"],
      domain: null,
      fightingStyle: "Stealth, speed, and lethal cursed tools",
      strengths: ["Undetectable", "Speed", "Power"],
      limitations: ["No techniques", "Human durability limits"],
      trivia: "Killed the strongest of his era temporarily.",
      relationships: ["Megumi", "Maki"],
      story: ["Hidden Inventory"],
      skills: {
        basic: { name: "Chain Strike", power: 1.2, energy: 0, type: "physical" },
        skill1: { name: "Playful Cloud", power: 1.8, energy: 5, type: "physical" },
        skill2: { name: "Inverted Spear", power: 2.0, energy: 8, type: "physical", effect: "pierce" },
        ultimate: { name: "Assassin's End", power: 2.8, energy: 12, type: "ultimate" },
        defense: { name: "Phantom Step", power: 0, energy: 5, type: "guard" }
      }
    },
    {
      id: "hakari",
      name: "Kinji Hakari",
      alias: "Idle Death Gamble",
      grade: "Grade 1 (potential Special)",
      affiliation: "Tokyo Jujutsu High",
      role: "Jackpot Fighter",
      rarity: "LEGENDARY",
      baseStats: { hp: 1200, atk: 950, def: 900, spd: 890, energy: 100 },
      description: "Lives for the thrill of the jackpot. Domain turns battle into a pachinko game of immortality.",
      personality: "Gambling addict, charismatic, free-spirited.",
      abilities: ["Idle Death Gamble", "Jackpot"],
      domain: "Idle Death Gamble",
      fightingStyle: "Risk-reward domain and endless regeneration",
      strengths: ["Immortality windows", "Pressure"],
      limitations: ["Luck dependent"],
      trivia: "Wants to make a fighting arena for sorcerers.",
      relationships: ["Kirara", "Yuta"],
      story: ["Culling Game"],
      skills: {
        basic: { name: "Casino Punch", power: 1.1, energy: 0, type: "physical" },
        skill1: { name: "Fever Mode", power: 1.5, energy: 20, type: "technique" },
        skill2: { name: "Pachinko Rush", power: 1.7, energy: 25, type: "physical" },
        ultimate: { name: "Jackpot Immortality", power: 2.6, energy: 50, type: "ultimate", effect: "regen" },
        defense: { name: "Lucky Guard", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "higuruma",
      name: "Hiromi Higuruma",
      alias: "Deadly Sentencing",
      grade: "Grade 1",
      affiliation: "Culling Game",
      role: "Judge",
      rarity: "EPIC",
      baseStats: { hp: 980, atk: 870, def: 920, spd: 800, energy: 110 },
      description: "Former lawyer who gained a domain that judges guilt. Fair, broken by the system, still seeks justice.",
      personality: "Exhausted idealist, calm under pressure.",
      abilities: ["Deadly Sentencing", "Confiscation", "Death Penalty"],
      domain: "Deadly Sentencing",
      fightingStyle: "Judgment and confiscation of techniques",
      strengths: ["Technique null", "Control"],
      limitations: ["Judgment rules"],
      trivia: "His domain is a courtroom of death.",
      relationships: ["Yuji"],
      story: ["Culling Game"],
      skills: {
        basic: { name: "Gavel Strike", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Confiscation", power: 1.3, energy: 25, type: "technique", effect: "null" },
        skill2: { name: "Judgment", power: 1.6, energy: 22, type: "technique" },
        ultimate: { name: "Death Penalty", power: 2.7, energy: 55, type: "ultimate" },
        defense: { name: "Court Barrier", power: 0, energy: 15, type: "guard" }
      }
    },
    {
      id: "yuki",
      name: "Yuki Tsukumo",
      alias: "Star Rage",
      grade: "Special Grade",
      affiliation: "Independent",
      role: "Mass Fighter",
      rarity: "LEGENDARY",
      baseStats: { hp: 1100, atk: 1050, def: 850, spd: 870, energy: 115 },
      description: "Special grade who believes in a different path for the jujutsu world. Star Rage adds virtual mass.",
      personality: "Free, philosophical, blunt.",
      abilities: ["Star Rage", "Garuda"],
      domain: null,
      fightingStyle: "Mass-enhanced punches and planetary scale force",
      strengths: ["Raw power", "Mass control"],
      limitations: ["Energy drain"],
      trivia: "One of the few special grades not tied to the schools.",
      relationships: ["Tengen", "Choso"],
      story: ["Perfect Preparation"],
      skills: {
        basic: { name: "Mass Punch", power: 1.2, energy: 0, type: "physical" },
        skill1: { name: "Star Boost", power: 1.7, energy: 22, type: "technique" },
        skill2: { name: "Garuda Strike", power: 1.8, energy: 25, type: "summon" },
        ultimate: { name: "Black Hole Punch", power: 3.0, energy: 60, type: "ultimate" },
        defense: { name: "Mass Shield", power: 0, energy: 15, type: "guard" }
      }
    },
    {
      id: "kashimo",
      name: "Hajime Kashimo",
      alias: "God of Lightning",
      grade: "Special Grade (potential)",
      affiliation: "Culling Game",
      role: "Lightning Assassin",
      rarity: "LEGENDARY",
      baseStats: { hp: 1020, atk: 1150, def: 820, spd: 1000, energy: 100 },
      description: "Ancient sorcerer revived for the Culling Game. Seeks only the strongest fight.",
      personality: "Battle-obsessed, respectful of strength.",
      abilities: ["Mythical Beast Amber", "Lightning"],
      domain: null,
      fightingStyle: "Lightning speed and one-time full power form",
      strengths: ["Speed", "Burst damage"],
      limitations: ["One-time transformation"],
      trivia: "Waited centuries for a worthy opponent.",
      relationships: ["Sukuna"],
      story: ["Culling Game"],
      skills: {
        basic: { name: "Lightning Jab", power: 1.2, energy: 0, type: "technique" },
        skill1: { name: "Thunderclap", power: 1.8, energy: 20, type: "technique" },
        skill2: { name: "Charge", power: 1.6, energy: 15, type: "physical", effect: "speed" },
        ultimate: { name: "Mythical Beast Amber", power: 3.1, energy: 55, type: "ultimate" },
        defense: { name: "Static Field", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "panda",
      name: "Panda",
      alias: "Cursed Corpse",
      grade: "Grade 2",
      affiliation: "Tokyo Jujutsu High",
      role: "Versatile Fighter",
      rarity: "RARE",
      baseStats: { hp: 1150, atk: 850, def: 950, spd: 750, energy: 80 },
      description: "A cursed corpse created by Principal Yaga. Has three cores and can shift modes.",
      personality: "Friendly, protective, surprisingly mature.",
      abilities: ["Core Shift", "Gorilla Mode"],
      domain: null,
      fightingStyle: "Mode switching between balance, power, and speed",
      strengths: ["Durability", "Modes"],
      limitations: ["Core destruction risk"],
      trivia: "Considers himself a real panda.",
      relationships: ["Yaga", "Maki", "Toge"],
      story: ["Kyoto Event", "Shibuya"],
      skills: {
        basic: { name: "Panda Punch", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Gorilla Mode", power: 1.7, energy: 20, type: "technique" },
        skill2: { name: "Core Shield", power: 0.8, energy: 15, type: "guard" },
        ultimate: { name: "Unleashed Cores", power: 2.3, energy: 40, type: "ultimate" },
        defense: { name: "Plush Guard", power: 0, energy: 10, type: "guard" }
      }
    },
    {
      id: "inumaki",
      name: "Toge Inumaki",
      alias: "Cursed Speech",
      grade: "Semi-Grade 1",
      affiliation: "Tokyo Jujutsu High",
      role: "Controller",
      rarity: "RARE",
      baseStats: { hp: 880, atk: 780, def: 750, spd: 820, energy: 95 },
      description: "Speaks only in rice ball ingredients to avoid accidental curses. Cursed Speech forces obedience.",
      personality: "Quiet, caring, expressive through limited words.",
      abilities: ["Cursed Speech"],
      domain: null,
      fightingStyle: "Command-based control and support",
      strengths: ["Control", "Support"],
      limitations: ["Throat damage", "Limited vocabulary in combat"],
      trivia: "Says 'salmon' for agreement.",
      relationships: ["Panda", "Maki", "Yuta"],
      story: ["Kyoto Event", "Shibuya"],
      skills: {
        basic: { name: "Silent Strike", power: 0.9, energy: 0, type: "physical" },
        skill1: { name: "Don't Move", power: 1.2, energy: 20, type: "technique", effect: "stun" },
        skill2: { name: "Explode", power: 1.8, energy: 25, type: "technique" },
        ultimate: { name: "Crush", power: 2.4, energy: 45, type: "ultimate" },
        defense: { name: "Silence", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "shoko",
      name: "Shoko Ieiri",
      alias: "The Doctor",
      grade: "Grade 1",
      affiliation: "Tokyo Jujutsu High",
      role: "Healer",
      rarity: "RARE",
      baseStats: { hp: 850, atk: 600, def: 700, spd: 780, energy: 120 },
      description: "Master of Reverse Cursed Technique. Keeps the school alive with her healing.",
      personality: "Dry, smoking, quietly reliable.",
      abilities: ["Reverse Cursed Technique"],
      domain: null,
      fightingStyle: "Support healing and limited combat",
      strengths: ["Healing", "RCT knowledge"],
      limitations: ["Low combat stats"],
      trivia: "Survived the same era as Gojo and Geto.",
      relationships: ["Gojo", "Geto", "Yaga"],
      story: ["Hidden Inventory", "Shibuya"],
      skills: {
        basic: { name: "Scalpel", power: 0.7, energy: 0, type: "physical" },
        skill1: { name: "Heal Ally", power: 0, energy: 25, type: "heal", effect: "heal" },
        skill2: { name: "RCT Pulse", power: 1.0, energy: 20, type: "technique" },
        ultimate: { name: "Full Restoration", power: 0, energy: 50, type: "heal", effect: "fullheal" },
        defense: { name: "Medical Guard", power: 0, energy: 10, type: "guard" }
      }
    },
    {
      id: "jogo",
      name: "Jogo",
      alias: "Disaster Flame",
      grade: "Special Grade",
      affiliation: "Disaster Curses",
      role: "Offense",
      rarity: "LEGENDARY",
      baseStats: { hp: 1050, atk: 1100, def: 720, spd: 880, energy: 115 },
      description: "Volcanic cursed spirit born from fear of natural disasters. Extremely proud and short-tempered.",
      personality: "Arrogant, furious, underestimates humans.",
      abilities: ["Disaster Flames", "Maximum Meteor", "Ember Insects"],
      domain: "Coffin of the Iron Mountain",
      fightingStyle: "Overwhelming heat and meteor strikes",
      strengths: ["Fire power", "Domain heat", "Speed"],
      limitations: ["Pride", "Compared to Sukuna"],
      trivia: "Wanted Sukuna's recognition.",
      relationships: ["Hanami", "Dagon", "Mahito", "Kenjaku"],
      story: ["Introduction", "Shibuya Incident"],
      skills: {
        basic: { name: "Ember Punch", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Disaster Flames", power: 1.7, energy: 25, type: "technique" },
        skill2: { name: "Ember Insects", power: 1.5, energy: 22, type: "technique", effect: "dot" },
        ultimate: { name: "Maximum Meteor", power: 3.0, energy: 60, type: "ultimate" },
        defense: { name: "Magma Shell", power: 0, energy: 15, type: "guard" }
      }
    },
    {
      id: "hanami",
      name: "Hanami",
      alias: "Disaster Plant",
      grade: "Special Grade",
      affiliation: "Disaster Curses",
      role: "Tank / Control",
      rarity: "LEGENDARY",
      baseStats: { hp: 1200, atk: 920, def: 980, spd: 750, energy: 110 },
      description: "Cursed spirit of forest fear. Calm, philosophical, protects nature through destruction.",
      personality: "Quiet, idealistic, relentless.",
      abilities: ["Plant Manipulation", "Cursed Bud", "Roots"],
      domain: null,
      fightingStyle: "Zone control and regenerative roots",
      strengths: ["Defense", "Area control", "Durability"],
      limitations: ["Slower than peers"],
      trivia: "Flower eye blooms under stress.",
      relationships: ["Jogo", "Dagon", "Mahito"],
      story: ["Kyoto Event", "Shibuya Incident"],
      skills: {
        basic: { name: "Root Strike", power: 0.95, energy: 0, type: "physical" },
        skill1: { name: "Cursed Bud", power: 1.4, energy: 22, type: "technique", effect: "dot" },
        skill2: { name: "Flower Field", power: 1.6, energy: 28, type: "technique" },
        ultimate: { name: "Wooden Ball", power: 2.6, energy: 55, type: "ultimate" },
        defense: { name: "Bark Armor", power: 0, energy: 14, type: "guard" }
      }
    },
    {
      id: "dagon",
      name: "Dagon",
      alias: "Disaster Tide",
      grade: "Special Grade",
      affiliation: "Disaster Curses",
      role: "Domain Specialist",
      rarity: "LEGENDARY",
      baseStats: { hp: 1100, atk: 980, def: 850, spd: 820, energy: 118 },
      description: "Evolved from a cursed womb. Ocean domain specialist with endless shikigami fish.",
      personality: "Childlike then vengeful after evolution.",
      abilities: ["Death Swarm", "Water Manipulation", "Horizon Domain"],
      domain: "Horizon of the Captivating Skandha",
      fightingStyle: "Drown enemies in domain and swarms",
      strengths: ["Domain", "AOE", "Endless summons"],
      limitations: ["Weaker outside domain"],
      trivia: "Fully matured during Shibuya.",
      relationships: ["Jogo", "Hanami", "Mahito"],
      story: ["Shibuya Incident"],
      skills: {
        basic: { name: "Tide Slap", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Death Swarm", power: 1.65, energy: 24, type: "technique" },
        skill2: { name: "Whirlpool", power: 1.55, energy: 26, type: "technique", effect: "pull" },
        ultimate: { name: "Horizon Skandha", power: 2.9, energy: 62, type: "ultimate", effect: "domain" },
        defense: { name: "Water Veil", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "kenjaku",
      name: "Kenjaku",
      alias: "The Body Hopper",
      grade: "Special Grade",
      affiliation: "Ancient Sorcerer",
      role: "Mastermind",
      rarity: "MYTHIC",
      baseStats: { hp: 1150, atk: 1000, def: 900, spd: 900, energy: 125 },
      description: "Thousand-year-old sorcerer who body-hops. Currently in Geto's body. Architect of the Culling Game.",
      personality: "Calm, curious, manipulative.",
      abilities: ["Cursed Spirit Manipulation", "Barrier Techniques", "Body Swap"],
      domain: "Womb Profusion",
      fightingStyle: "Spirit armies and perfect planning",
      strengths: ["Versatility", "Knowledge", "Army"],
      limitations: ["Body-dependent"],
      trivia: "One of the oldest active sorcerers.",
      relationships: ["Geto (body)", "Mahito", "Sukuna", "Tengen"],
      story: ["Shibuya", "Culling Game"],
      skills: {
        basic: { name: "Spirit Strike", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Spirit Swarm", power: 1.6, energy: 25, type: "technique" },
        skill2: { name: "Maximum Uzumaki", power: 2.0, energy: 35, type: "technique" },
        ultimate: { name: "Womb Profusion", power: 3.1, energy: 65, type: "ultimate", effect: "domain" },
        defense: { name: "Barrier Wall", power: 0, energy: 15, type: "guard" }
      }
    },
    {
      id: "naoya",
      name: "Naoya Zenin",
      alias: "The Prodigy",
      grade: "Special Grade (Curse)",
      affiliation: "Zenin / Cursed Spirit",
      role: "Speed Assassin",
      rarity: "LEGENDARY",
      baseStats: { hp: 980, atk: 1050, def: 780, spd: 1100, energy: 105 },
      description: "Zenin prodigy who became a vengeful curse. Projection Sorcery at 24 frames.",
      personality: "Arrogant, sexist, obsessed with superiority.",
      abilities: ["Projection Sorcery", "24 FPS", "Time Cell Moon Palace"],
      domain: "Time Cell Moon Palace",
      fightingStyle: "Frame-perfect blitz and freeze",
      strengths: ["Speed", "Domain", "Precision"],
      limitations: ["Ego", "Predictable patterns"],
      trivia: "Hates Maki for surpassing him.",
      relationships: ["Maki", "Zenin Clan", "Toji"],
      story: ["Perfect Preparation", "Culling Game"],
      skills: {
        basic: { name: "Frame Punch", power: 1.05, energy: 0, type: "physical" },
        skill1: { name: "Projection Step", power: 1.5, energy: 20, type: "technique", effect: "stun" },
        skill2: { name: "24-Cut", power: 1.75, energy: 28, type: "technique" },
        ultimate: { name: "Time Cell Moon Palace", power: 2.85, energy: 58, type: "ultimate", effect: "domain" },
        defense: { name: "Frame Guard", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "uraume",
      name: "Uraume",
      alias: "The Frozen Star",
      grade: "Special Grade",
      affiliation: "Sukuna's Servant",
      role: "Ice Control",
      rarity: "LEGENDARY",
      baseStats: { hp: 1000, atk: 1020, def: 860, spd: 920, energy: 120 },
      description: "Loyal servant of Sukuna for a thousand years. Master of ice and frost techniques.",
      personality: "Cold, devoted, efficient.",
      abilities: ["Ice Formation", "Frost Calm", "Frozen Blade"],
      domain: null,
      fightingStyle: "Area freeze and precise ice spears",
      strengths: ["Control", "Burst damage", "Loyalty buff near Sukuna"],
      limitations: ["Rarely fights alone at full power"],
      trivia: "Cooks for Sukuna.",
      relationships: ["Sukuna", "Kenjaku"],
      story: ["Shibuya", "Shinjuku Showdown"],
      skills: {
        basic: { name: "Ice Shard", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Frost Calm", power: 1.45, energy: 22, type: "technique", effect: "stun" },
        skill2: { name: "Ice Coffin", power: 1.7, energy: 28, type: "technique" },
        ultimate: { name: "Glacial Hell", power: 2.8, energy: 58, type: "ultimate" },
        defense: { name: "Frost Armor", power: 0, energy: 14, type: "guard" }
      }
    },
    {
      id: "ryu",
      name: "Ryu Ishigori",
      alias: "The Granite Blast",
      grade: "Grade 1+",
      affiliation: "Culling Game Player",
      role: "Artillery",
      rarity: "EPIC",
      baseStats: { hp: 1080, atk: 1120, def: 800, spd: 840, energy: 100 },
      description: "Ancient sorcerer obsessed with satisfying battles. Fires devastating granite blasts.",
      personality: "Battle-hungry, honorable, straightforward.",
      abilities: ["Granite Blast", "Cursed Energy Discharge"],
      domain: null,
      fightingStyle: "Long-range high-output beams",
      strengths: ["Raw output", "Range"],
      limitations: ["Less versatile up close"],
      trivia: "Wanted a satisfying fight more than victory.",
      relationships: ["Uro", "Yuta", "Takaba"],
      story: ["Culling Game"],
      skills: {
        basic: { name: "Stone Fist", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Granite Blast", power: 1.8, energy: 28, type: "technique" },
        skill2: { name: "Full Discharge", power: 1.9, energy: 32, type: "technique" },
        ultimate: { name: "Maximum Output Blast", power: 2.9, energy: 60, type: "ultimate" },
        defense: { name: "Granite Guard", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "uro",
      name: "Takako Uro",
      alias: "Sky Manipulation",
      grade: "Grade 1+",
      affiliation: "Culling Game Player",
      role: "Control",
      rarity: "EPIC",
      baseStats: { hp: 1020, atk: 980, def: 820, spd: 900, energy: 108 },
      description: "Former Fujiwara assassin. Manipulates the sky itself as a surface.",
      personality: "Bitter, sharp, proud of her clan history.",
      abilities: ["Sky Manipulation", "Thin Ice Breaker"],
      domain: null,
      fightingStyle: "Surface control and aerial dominance",
      strengths: ["Zone control", "Mobility"],
      limitations: ["Emotional triggers"],
      trivia: "Hated being treated as a tool.",
      relationships: ["Ryu", "Yuta"],
      story: ["Culling Game"],
      skills: {
        basic: { name: "Sky Slash", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Sky Hand", power: 1.55, energy: 24, type: "technique", effect: "knockback" },
        skill2: { name: "Thin Ice Breaker", power: 1.75, energy: 30, type: "technique" },
        ultimate: { name: "Sky Collapse", power: 2.7, energy: 55, type: "ultimate" },
        defense: { name: "Sky Barrier", power: 0, energy: 14, type: "guard" }
      }
    },
    {
      id: "meimei",
      name: "Mei Mei",
      alias: "The Crow Mistress",
      grade: "Grade 1",
      affiliation: "Independent",
      role: "Support / Assassin",
      rarity: "EPIC",
      baseStats: { hp: 950, atk: 1000, def: 780, spd: 890, energy: 105 },
      description: "Money-driven Grade 1 sorcerer. Uses crows and a massive axe with perfect precision.",
      personality: "Greedy, calm, professional.",
      abilities: ["Black Bird Manipulation", "Cursed Tool Axe"],
      domain: null,
      fightingStyle: "Bird surveillance and decisive axe strikes",
      strengths: ["Intel", "Burst"],
      limitations: ["Motivated by payment"],
      trivia: "Charges for every service.",
      relationships: ["Ui Ui", "Gojo"],
      story: ["Shibuya Incident"],
      skills: {
        basic: { name: "Axe Swing", power: 1.05, energy: 0, type: "physical" },
        skill1: { name: "Bird Strike", power: 1.5, energy: 20, type: "technique" },
        skill2: { name: "Bird Bomb", power: 1.85, energy: 30, type: "technique" },
        ultimate: { name: "Bird Strike Massacre", power: 2.6, energy: 52, type: "ultimate" },
        defense: { name: "Crow Screen", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "angel",
      name: "Angel / Hana Kurusu",
      alias: "The Technique Extinguisher",
      grade: "Special Grade",
      affiliation: "Culling Game",
      role: "Anti-Technique",
      rarity: "LEGENDARY",
      baseStats: { hp: 980, atk: 940, def: 820, spd: 910, energy: 115 },
      description: "Incarnated angel whose technique extinguishes other cursed techniques. Host is Hana Kurusu.",
      personality: "Hana: kind. Angel: blunt and mission-focused.",
      abilities: ["Technique Extinguishment", "Jacob's Ladder"],
      domain: null,
      fightingStyle: "Nullify techniques then punish",
      strengths: ["Anti-CT", "Support"],
      limitations: ["Host conflict"],
      trivia: "Key to sealing Sukuna's techniques temporarily.",
      relationships: ["Megumi", "Yuji", "Sukuna"],
      story: ["Culling Game", "Shinjuku"],
      skills: {
        basic: { name: "Light Strike", power: 0.95, energy: 0, type: "physical" },
        skill1: { name: "Extinguish", power: 1.3, energy: 25, type: "technique", effect: "stun" },
        skill2: { name: "Sacred Beam", power: 1.7, energy: 28, type: "technique" },
        ultimate: { name: "Jacob's Ladder", power: 2.9, energy: 60, type: "ultimate" },
        defense: { name: "Holy Veil", power: 0, energy: 14, type: "guard" }
      }
    },
    {
      id: "mai",
      name: "Mai Zenin",
      alias: "Construction",
      grade: "Grade 3",
      affiliation: "Kyoto Jujutsu High / Zenin",
      role: "Support",
      rarity: "RARE",
      baseStats: { hp: 820, atk: 780, def: 720, spd: 800, energy: 95 },
      description: "Maki's twin. Creates objects from cursed energy. Complicated bond with her sister.",
      personality: "Bitter, sharp, lonely under the surface.",
      abilities: ["Construction", "Bullet Creation"],
      domain: null,
      fightingStyle: "Ranged creation bullets",
      strengths: ["Surprise rounds", "Support fire"],
      limitations: ["Low CE reserves"],
      trivia: "Gave her life so Maki could fully awaken.",
      relationships: ["Maki", "Zenin Clan"],
      story: ["Kyoto Event", "Perfect Preparation"],
      skills: {
        basic: { name: "Strike", power: 0.9, energy: 0, type: "physical" },
        skill1: { name: "CE Bullet", power: 1.4, energy: 18, type: "technique" },
        skill2: { name: "Rapid Fire", power: 1.55, energy: 24, type: "technique" },
        ultimate: { name: "Last Round", power: 2.3, energy: 45, type: "ultimate" },
        defense: { name: "Cover", power: 0, energy: 10, type: "guard" }
      }
    },
    {
      id: "miwa",
      name: "Kasumi Miwa",
      alias: "New Shadow Style",
      grade: "Grade 3",
      affiliation: "Kyoto Jujutsu High",
      role: "Swordsman",
      rarity: "RARE",
      baseStats: { hp: 880, atk: 820, def: 760, spd: 840, energy: 90 },
      description: "Hardworking swordswoman of Kyoto. Simple Domain user, dreams of a stable job.",
      personality: "Earnest, nervous, determined.",
      abilities: ["New Shadow Style", "Simple Domain"],
      domain: null,
      fightingStyle: "Iai draws and Simple Domain defense",
      strengths: ["Defense", "Discipline"],
      limitations: ["Power ceiling"],
      trivia: "Wants a salaryman life.",
      relationships: ["Mechamaru", "Utahime", "Todo"],
      story: ["Kyoto Event", "Shibuya"],
      skills: {
        basic: { name: "Draw Slash", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Batto Sword Drawing", power: 1.5, energy: 20, type: "technique" },
        skill2: { name: "Simple Domain", power: 0.8, energy: 22, type: "technique", effect: "stun" },
        ultimate: { name: " sequentially Slash", power: 2.2, energy: 48, type: "ultimate" },
        defense: { name: "Simple Domain Guard", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "mechamaru",
      name: "Kokichi Muta / Mechamaru",
      alias: "Ultimate Mechamaru",
      grade: "Grade 1",
      affiliation: "Kyoto Jujutsu High",
      role: "Artillery",
      rarity: "EPIC",
      baseStats: { hp: 1000, atk: 1050, def: 900, spd: 780, energy: 115 },
      description: "Heavenly Restriction: broken body, extreme CE. Pilots Ultimate Mechamaru puppets.",
      personality: "Lonely, strategic, longs for a normal body.",
      abilities: ["Puppet Manipulation", "Ultra Cannon", "Mode: Absolute"],
      domain: null,
      fightingStyle: "Long-range puppet warfare",
      strengths: ["Range", "Firepower", "Planning"],
      limitations: ["Body dependency"],
      trivia: "Made a binding vow with Mahito.",
      relationships: ["Miwa", "Mahito", "Kyoto students"],
      story: ["Kyoto Event", "Shibuya"],
      skills: {
        basic: { name: "Mecha Punch", power: 1.0, energy: 0, type: "physical" },
        skill1: { name: "Ultra Cannon", power: 1.75, energy: 26, type: "technique" },
        skill2: { name: "Missile Barrage", power: 1.65, energy: 28, type: "technique" },
        ultimate: { name: "Mode Absolute", power: 2.85, energy: 60, type: "ultimate" },
        defense: { name: "Armor Plate", power: 0, energy: 14, type: "guard" }
      }
    },
    {
      id: "utahime",
      name: "Utahime Iori",
      alias: "Solo Forbidden Area",
      grade: "Grade 1",
      affiliation: "Kyoto Jujutsu High",
      role: "Buffer",
      rarity: "EPIC",
      baseStats: { hp: 920, atk: 800, def: 840, spd: 820, energy: 110 },
      description: "Kyoto teacher. Her technique amplifies allies' cursed energy output through song.",
      personality: "Strict, caring, easily annoyed by Gojo.",
      abilities: ["Solo Forbidden Area", "Support Buff"],
      domain: null,
      fightingStyle: "Ally amplification and coordination",
      strengths: ["Team buffs", "Leadership"],
      limitations: ["Needs allies nearby"],
      trivia: "Often dragged into Gojo's jokes.",
      relationships: ["Gojo", "Gakuganji", "Kyoto students"],
      story: ["Kyoto Event", "Shibuya", "Shinjuku"],
      skills: {
        basic: { name: "Talisman Strike", power: 0.9, energy: 0, type: "physical" },
        skill1: { name: "CE Amplify", power: 1.2, energy: 22, type: "technique" },
        skill2: { name: "Solo Verse", power: 1.4, energy: 26, type: "technique" },
        ultimate: { name: "Solo Forbidden Area", power: 2.4, energy: 55, type: "ultimate" },
        defense: { name: "Ward", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "takaba",
      name: "Fumihiko Takaba",
      alias: "Comedian",
      grade: "Special Grade",
      affiliation: "Culling Game",
      role: "Reality Warper",
      rarity: "LEGENDARY",
      baseStats: { hp: 1100, atk: 900, def: 900, spd: 850, energy: 120 },
      description: "Failed comedian whose technique makes whatever he finds funny become real.",
      personality: "Awkward, sincere, unexpectedly brave.",
      abilities: ["Comedian", "Reality Gag"],
      domain: null,
      fightingStyle: "Unpredictable comedy-based reality shifts",
      strengths: ["Unpredictable", "High ceiling"],
      limitations: ["Needs to find it funny"],
      trivia: "Fought Kenjaku to a standstill in spirit.",
      relationships: ["Kenjaku", "Yuta"],
      story: ["Culling Game"],
      skills: {
        basic: { name: "Slapstick", power: 0.95, energy: 0, type: "physical" },
        skill1: { name: "Gag Setup", power: 1.4, energy: 22, type: "technique", effect: "stun" },
        skill2: { name: "Punchline", power: 1.7, energy: 28, type: "technique" },
        ultimate: { name: "Comedian Reality", power: 2.9, energy: 60, type: "ultimate" },
        defense: { name: "Safety Prop", power: 0, energy: 12, type: "guard" }
      }
    },
    {
      id: "yorozu",
      name: "Yorozu",
      alias: "Construction Goddess",
      grade: "Special Grade",
      affiliation: "Heian Era / Culling Game",
      role: "Construction Combat",
      rarity: "LEGENDARY",
      baseStats: { hp: 1120, atk: 1080, def: 880, spd: 900, energy: 118 },
      description: "Heian-era sorcerer obsessed with Sukuna. Perfect liquid metal construction.",
      personality: "Obsessive, dramatic, battle-loving.",
      abilities: ["Construction", "True Sphere", "Liquid Metal Armor"],
      domain: null,
      fightingStyle: "Perfect constructs and domain pressure",
      strengths: ["Versatile constructs", "Offense"],
      limitations: ["Emotion-driven"],
      trivia: "Wanted Sukuna's love through combat.",
      relationships: ["Sukuna", "Uraume"],
      story: ["Culling Game"],
      skills: {
        basic: { name: "Metal Strike", power: 1.05, energy: 0, type: "physical" },
        skill1: { name: "Liquid Spear", power: 1.65, energy: 24, type: "technique" },
        skill2: { name: "True Sphere", power: 1.9, energy: 32, type: "technique" },
        ultimate: { name: "Perfect Construction", power: 2.95, energy: 62, type: "ultimate" },
        defense: { name: "Metal Armor", power: 0, energy: 14, type: "guard" }
      }
    },
    {
      id: "junpei",
      name: "Junpei Yoshino",
      alias: "Shikigami User",
      grade: "Grade 4+",
      affiliation: "Civilian / Temporary",
      role: "Shikigami",
      rarity: "RARE",
      baseStats: { hp: 800, atk: 750, def: 700, spd: 780, energy: 95 },
      description: "Bullied student who met Mahito. Used Moon Dregs shikigami. Tragic path.",
      personality: "Kind, angry at the world, conflicted.",
      abilities: ["Moon Dregs", "Poison"],
      domain: null,
      fightingStyle: "Shikigami poison pressure",
      strengths: ["Poison DoT", "Reach"],
      limitations: ["Inexperienced"],
      trivia: "Yuji tried to save him.",
      relationships: ["Yuji", "Mahito", "Nagi Yoshino"],
      story: ["Vs Mahito"],
      skills: {
        basic: { name: "Punch", power: 0.85, energy: 0, type: "physical" },
        skill1: { name: "Moon Dregs", power: 1.35, energy: 18, type: "technique" },
        skill2: { name: "Poison Mist", power: 1.45, energy: 22, type: "technique", effect: "dot" },
        ultimate: { name: "Moon Dregs Rage", power: 2.1, energy: 42, type: "ultimate" },
        defense: { name: "Guard", power: 0, energy: 10, type: "guard" }
      }
    },
    {
      id: "uiui",
      name: "Ui Ui",
      alias: "Mei Mei's Brother",
      grade: "Grade 2",
      affiliation: "Independent",
      role: "Support",
      rarity: "RARE",
      baseStats: { hp: 780, atk: 720, def: 700, spd: 860, energy: 100 },
      description: "Mei Mei's little brother. Teleportation and support under her orders.",
      personality: "Devoted to Mei Mei, quiet, efficient.",
      abilities: ["Teleport", "Support Carry"],
      domain: null,
      fightingStyle: "Reposition and assist",
      strengths: ["Mobility", "Utility"],
      limitations: ["Follows Mei Mei's lead"],
      trivia: "Calls Mei Mei 'Big Sis' with extreme loyalty.",
      relationships: ["Mei Mei"],
      story: ["Shibuya Incident"],
      skills: {
        basic: { name: "Strike", power: 0.9, energy: 0, type: "physical" },
        skill1: { name: "Teleport Tag", power: 1.2, energy: 18, type: "technique" },
        skill2: { name: "Swap", power: 1.3, energy: 22, type: "technique" },
        ultimate: { name: "Emergency Warp", power: 2.0, energy: 40, type: "ultimate" },
        defense: { name: "Blink Guard", power: 0, energy: 10, type: "guard" }
      }
    }
  ],

  techniques: [
    { id: "limitless", name: "Limitless", users: ["gojo"], type: "Innate", description: "Manipulates space at the atomic level. Infinity creates an infinite series between self and attack.", mechanics: "Automatic defense + offensive Blue/Red", combatRole: "Defense & Control", strengths: ["Near-absolute defense"], limitations: ["Requires Six Eyes for efficiency"], related: ["Six Eyes", "Blue", "Red", "Hollow Purple"] },
    { id: "sixeyes", name: "Six Eyes", users: ["gojo"], type: "Inherited", description: "Allows precise perception and near-zero energy cost for Limitless.", mechanics: "Perception + efficiency", combatRole: "Support for Limitless", strengths: ["Efficiency"], limitations: ["Mental strain"], related: ["Limitless"] },
    { id: "blue", name: "Blue", users: ["gojo"], type: "Technique", description: "Attractive force that pulls matter and energy.", mechanics: "Negative space", combatRole: "Control / Setup", strengths: ["Pull"], limitations: ["Energy cost"], related: ["Limitless"] },
    { id: "red", name: "Red", users: ["gojo"], type: "Technique", description: "Repulsive force that blasts targets away.", mechanics: "Positive space", combatRole: "Offense", strengths: ["Knockback"], limitations: ["Harder to use"], related: ["Limitless"] },
    { id: "purple", name: "Hollow Technique: Purple", users: ["gojo"], type: "Imaginary", description: "Collision of Blue and Red creates erasure.", mechanics: "Imaginary mass", combatRole: "Ultimate", strengths: ["Erasure"], limitations: ["High cost"], related: ["Blue", "Red"] },
    { id: "tenshadows", name: "Ten Shadows Technique", users: ["megumi"], type: "Inherited", description: "Summons shikigami from shadows. Potential to tame Mahoraga.", mechanics: "Shadow storage & summon", combatRole: "Versatile summon", strengths: ["Adaptability"], limitations: ["Shikigami loss"], related: ["Chimera Shadow Garden"] },
    { id: "strawdoll", name: "Straw Doll Technique", users: ["nobara"], type: "Innate", description: "Uses nails, hammer, and straw dolls to resonate damage.", mechanics: "Link damage", combatRole: "Ranged / Link", strengths: ["Distance"], limitations: ["Setup needed"], related: ["Resonance"] },
    { id: "ratio", name: "Ratio Technique", users: ["nanami"], type: "Innate", description: "Creates a weak point at 7:3 ratio on any target.", mechanics: "Forced critical", combatRole: "Critical striker", strengths: ["Consistency"], limitations: ["Pattern"], related: [] },
    { id: "cursedspeech", name: "Cursed Speech", users: ["inumaki"], type: "Inherited", description: "Forces targets to obey spoken commands.", mechanics: "Forced action", combatRole: "Control", strengths: ["Instant control"], limitations: ["Throat damage"], related: [] },
    { id: "bloodmanip", name: "Blood Manipulation", users: ["choso"], type: "Innate", description: "Controls own blood as weapon and projectile.", mechanics: "Blood shaping", combatRole: "Mid-range control", strengths: ["Sustained"], limitations: ["Blood volume"], related: [] },
    { id: "boogie", name: "Boogie Woogie", users: ["todo"], type: "Innate", description: "Swaps positions of anything with cursed energy on clap.", mechanics: "Teleport swap", combatRole: "Disruption", strengths: ["Chaos"], limitations: ["Telegraphed"], related: [] },
    { id: "csm", name: "Cursed Spirit Manipulation", users: ["geto"], type: "Innate", description: "Absorbs and commands cursed spirits.", mechanics: "Spirit army", combatRole: "Army control", strengths: ["Numbers"], limitations: ["Quality"], related: ["Uzumaki"] },
    { id: "idletrans", name: "Idle Transfiguration", users: ["mahito"], type: "Innate", description: "Touches and reshapes the soul, altering the body.", mechanics: "Soul damage", combatRole: "Soul attacker", strengths: ["Bypass durability"], limitations: ["Contact needed"], related: ["Self-Embodiment"] },
    { id: "copy", name: "Copy", users: ["yuta"], type: "Innate", description: "Copies techniques under certain conditions via Rika.", mechanics: "Technique theft", combatRole: "Adaptive", strengths: ["Versatility"], limitations: ["Conditions"], related: ["Rika"] },
    { id: "rct", name: "Reverse Cursed Technique", users: ["gojo", "yuta", "shoko", "sukuna"], type: "Advanced", description: "Multiplies negative energy to produce positive energy for healing.", mechanics: "Healing / anti-curse", combatRole: "Support / Sustain", strengths: ["Healing"], limitations: ["Skill required"], related: [] },
    { id: "starrage", name: "Star Rage", users: ["yuki"], type: "Innate", description: "Adds virtual mass to self and shikigami.", mechanics: "Mass amplification", combatRole: "Power", strengths: ["Force"], limitations: ["Energy"], related: [] },
    { id: "projection", name: "Projection Sorcery", users: ["naoya"], type: "Inherited", description: "Divides 1 second into 24 frames; freezes those who cannot keep up.", mechanics: "Frame lock", combatRole: "Speed control", strengths: ["Freeze"], limitations: ["Frame limit"], related: [] },
    { id: "comedian", name: "Comedian", users: ["ugo"], type: "Innate", description: "Reality warps based on what the user finds funny.", mechanics: "Subjective reality", combatRole: "Wildcard", strengths: ["Unpredictable"], limitations: ["Mood dependent"], related: [] }
  ],

  domains: [
    { id: "unlimitedvoid", name: "Unlimited Void", user: "gojo", theme: "void", concept: "Infinite information flood inside an absolute barrier", effect: "Target is paralyzed by endless sensory input", combat: "Instant incapacitation of anyone caught inside", mechanics: "Sure-hit information overload via Limitless", relatedTech: "Limitless / Six Eyes", grade: "Special Grade" },
    { id: "malevolent", name: "Malevolent Shrine", user: "sukuna", theme: "shrine", concept: "Open-barrier domain of pure slaughter", effect: "Dismantle and Cleave rain continuously", combat: "AOE annihilation across a wide radius", mechanics: "No closed barrier — range-based sure-hit", relatedTech: "Dismantle / Cleave", grade: "Special Grade" },
    { id: "selfembodiment", name: "Self-Embodiment of Perfection", user: "mahito", theme: "perfection", concept: "Domain that forces soul contact", effect: "Guaranteed Idle Transfiguration on hit", combat: "Rewrite the shape of the soul", mechanics: "Sure-hit soul touch inside the barrier", relatedTech: "Idle Transfiguration", grade: "Special Grade" },
    { id: "chimera", name: "Chimera Shadow Garden", user: "megumi", theme: "shadow", concept: "Expanded shadow dimension as battlefield", effect: "Shikigami empowered, shadows become weapons", combat: "Ambush and overwhelm through shadows", mechanics: "Incomplete domain — still extremely lethal", relatedTech: "Ten Shadows Technique", grade: "Semi-Grade 1+" },
    { id: "idlegamble", name: "Idle Death Gamble", user: "hakari", theme: "gamble", concept: "Pachinko-machine domain of pure chance", effect: "Jackpot grants near-immortality via endless RCT", combat: "Outlast and crush during jackpot windows", mechanics: "Probability-driven; visual pachinko symbols", relatedTech: "Idle Death Gamble", grade: "Special Grade" },
    { id: "deadlysentence", name: "Deadly Sentencing", user: "higuruma", theme: "court", concept: "Courtroom domain that judges the guilty", effect: "Confiscation of technique or Death Penalty sword", combat: "Nullify cursed techniques then execute", mechanics: "Judgment rules decide the sentence", relatedTech: "Confiscation / Gavel", grade: "Special Grade" },
    { id: "authenticlove", name: "Authentic Mutual Love", user: "yuta", theme: "love", concept: "Domain filled with copied techniques and Rika", effect: "Full access to copied arsenal + Rika manifestation", combat: "Overwhelm with variety and raw power", mechanics: "Sure-hit selection of copied techniques", relatedTech: "Copy / Rika", grade: "Special Grade" },
    { id: "horizon", name: "Horizon of the Captivating Skandha", user: "dagon", theme: "ocean", concept: "Tropical ocean domain of a cursed spirit", effect: "Death Swarm of countless shikigami fish", combat: "Drown and pierce from every angle", mechanics: "Sure-hit aquatic projectiles", relatedTech: "Death Swarm", grade: "Special Grade" },
    { id: "coffin", name: "Coffin of the Iron Mountain", user: "jogo", theme: "volcano", concept: "Volcanic domain of extreme heat", effect: "Incinerate everything inside with magma and fire", combat: "Maximum Meteor support + domain heat", mechanics: "Sure-hit scorching environment", relatedTech: "Disaster Flames", grade: "Special Grade" },
    { id: "timecell", name: "Time Cell Moon Palace", user: "naoya", theme: "void", concept: "24-frame projection domain", effect: "Guaranteed Projection Sorcery hits", combat: "Freeze motion then slice at frame-perfect timing", mechanics: "Sure-hit based on 24 fps rule", relatedTech: "Projection Sorcery", grade: "Special Grade" },
    { id: "wombprofusion", name: "Womb Profusion", user: "kenjaku", theme: "shrine", concept: "Domain that compresses cursed spirits into Uzumaki", effect: "Devastating compressed spirit blast", combat: "One-shot level projectile after compression", mechanics: "Spirit compression inside barrier", relatedTech: "Cursed Spirit Manipulation", grade: "Special Grade" }
  ],

  storyArcs: [
    { id: "jjk0", title: "Jujutsu Kaisen 0 / Cursed Child", timeline: "Before main series", summary: "Yuta Okkotsu, haunted by Rika, enters jujutsu high and confronts Geto's ideology.", characters: ["yuta", "maki", "inumaki", "panda", "geto", "gojo"], events: ["Rika release", "Geto attack", "Yuta special grade"], unlocks: ["yuta"], progress: 0 },
    { id: "intro", title: "Introduction", timeline: "Start", summary: "Yuji swallows Sukuna's finger and is thrown into the world of curses under Gojo's wing.", characters: ["yuji", "megumi", "nobara", "gojo", "sukuna"], events: ["Finger consumption", "First mission"], unlocks: ["yuji", "megumi", "nobara"], progress: 0 },
    { id: "mahito", title: "Vs Mahito / Junpei", timeline: "Early", summary: "Yuji faces the soul-manipulating curse Mahito and the tragedy of Junpei.", characters: ["yuji", "nanami", "mahito"], events: ["Junpei tragedy", "First Mahito fight"], unlocks: ["nanami", "mahito"], progress: 0 },
    { id: "kyoto", title: "Kyoto Goodwill Event", timeline: "Mid early", summary: "Tokyo and Kyoto students clash in a goodwill event that turns serious with curse attacks.", characters: ["yuji", "megumi", "nobara", "todo", "maki", "panda", "inumaki"], events: ["Todo brotherhood", "Hanami appearance"], unlocks: ["todo", "panda", "inumaki"], progress: 0 },
    { id: "deathpainting", title: "Death Painting", timeline: "Mid", summary: "The Death Painting Wombs awaken. Choso begins his path toward brotherhood with Yuji.", characters: ["yuji", "nobara", "choso"], events: ["Eso & Kechizu", "Choso birth"], unlocks: ["choso"], progress: 0 },
    { id: "hidden", title: "Hidden Inventory / Premature Death", timeline: "Past", summary: "Gojo and Geto's past. The star plasma vessel mission that shattered their bond.", characters: ["gojo", "geto", "toji", "shoko"], events: ["Toji ambush", "Geto's fall"], unlocks: ["toji", "geto"], progress: 0 },
    { id: "shibuya", title: "Shibuya Incident", timeline: "Climax early", summary: "A massive curse plot in Shibuya. Gojo sealed, many fall, Sukuna rampages.", characters: ["gojo", "yuji", "megumi", "nobara", "nanami", "todo", "mahito", "choso", "sukuna"], events: ["Gojo sealed", "Nanami fall", "Sukuna 15F"], unlocks: [], progress: 0 },
    { id: "extermination", title: "Itadori Extermination", timeline: "Post-Shibuya", summary: "Yuji is hunted. Allies scramble while the higher-ups move.", characters: ["yuji", "choso", "yuta"], events: ["Yuta 'execution'"], unlocks: [], progress: 0 },
    { id: "perfect", title: "Perfect Preparation", timeline: "Transition", summary: "Preparation for the Culling Game. Maki's transformation and new alliances.", characters: ["maki", "yuki", "choso"], events: ["Maki rebirth", "Tengen deal"], unlocks: ["maki", "yuki"], progress: 0 },
    { id: "culling", title: "Culling Game", timeline: "Mid-late", summary: "A deadly game across Japan. New players, ancient sorcerers, and shifting rules.", characters: ["yuji", "megumi", "yuta", "hakari", "higuruma", "kashimo", "sukuna"], events: ["Colonies open", "Sukuna vessel change"], unlocks: ["hakari", "higuruma", "kashimo"], progress: 0 },
    { id: "shinjuku", title: "Shinjuku Showdown", timeline: "Finale", summary: "The final confrontation. Strongest vs strongest in a battle that decides the future.", characters: ["gojo", "sukuna", "yuji", "yuta", "hakari", "maki"], events: ["Gojo vs Sukuna", "Final choices"], unlocks: [], progress: 0 }
  ],

  rarities: {
    COMMON: { color: "#9ca3af", chance: 45, label: "COMMON" },
    UNCOMMON: { color: "#22c55e", chance: 25, label: "UNCOMMON" },
    RARE: { color: "#3b82f6", chance: 15, label: "RARE" },
    EPIC: { color: "#a855f7", chance: 9, label: "EPIC" },
    LEGENDARY: { color: "#f59e0b", chance: 4.5, label: "LEGENDARY" },
    MYTHIC: { color: "#ef4444", chance: 1.3, label: "MYTHIC" },
    LIMITED: { color: "#ec4899", chance: 0.2, label: "LIMITED" }
  },

  quests: [
    { id: "q1", title: "Win a Battle", desc: "Complete 1 battle victory", type: "daily", target: 1, reward: "battlesWon", rewards: { xp: 100, coins: 50, gems: 5 } },
    { id: "q2", title: "Train a Character", desc: "Complete any training once", type: "daily", target: 1, progress: "trainsDone", rewards: { xp: 80, coins: 40, gems: 3 } },
    { id: "q3", title: "Summon Once", desc: "Perform 1 summon", type: "daily", target: 1, progress: "summonsDone", rewards: { xp: 60, coins: 30, gems: 10 } },
    { id: "q4", title: "Upgrade a Card", desc: "Upgrade any character level", type: "daily", target: 1, progress: "upgradesDone", rewards: { xp: 90, coins: 60, gems: 5 } },
    { id: "q5", title: "Story Progress", desc: "Advance any story arc", type: "daily", target: 1, progress: "storyProgress", rewards: { xp: 120, coins: 80, gems: 8 } }
  ],

  dailyNews: [
    { id: "n1", tag: "BREAKING", title: "Shibuya residual cursed energy spikes", body: "Sensors detect lingering domains near Shibuya Station. Grade 1 teams advised to stay alert.", icon: "⚠️" },
    { id: "n2", tag: "MISSION", title: "New cursed spirit cluster in Sendai", body: "Multiple Grade 2 spirits reported. Students from Tokyo Jujutsu High dispatched.", icon: "🎯" },
    { id: "n3", tag: "INTEL", title: "Idle Death Gamble sightings", body: "Reports of a domain that never ends. Hakari technique remains under study.", icon: "🎰" },
    { id: "n4", tag: "UPDATE", title: "Gojo Infinity still unreplicable", body: "Six Eyes data remains classified. No sorcerer has matched the barrier density.", icon: "♾️" },
    { id: "n5", tag: "RUMOR", title: "King of Curses energy signature", body: "Faint traces matching Sukuna detected near former colony sites. Status unknown.", icon: "👑" },
    { id: "n6", tag: "TRAINING", title: "Black Flash training window open", body: "Higher chance of landing Black Flash during synchronized training sessions today.", icon: "⚡" },
    { id: "n7", tag: "DOMAIN", title: "Barrier research breakthrough", body: "New barrier formulas reduce CE cost by 12%. Applied to student training grounds.", icon: "🛡️" }
  ],

  battleDialogues: {
    gojo: [
      "Nah, I'd win.",
      "Throughout heaven and earth, I alone am the honored one.",
      "Are you the strongest because you're Satoru Gojo? Or are you Satoru Gojo because you're the strongest?",
      "Love is the most twisted curse of all.",
      "Yo, Success!",
      "I'm gonna have to kill you.",
      "Domain Expansion — Unlimited Void."
    ],
    yuji: [
      "I don't want to regret the way I live!",
      "I'm gonna save people... and make sure they get a proper death!",
      "Black Flash!",
      "You're me... I'm you.",
      "I am you!",
      "It might be for the best if I just die!",
      "Sukuna... I'm taking everything back!"
    ],
    megumi: [
      "With this treasure I summon...",
      "Divine Dogs!",
      "I won't let anyone die.",
      "Mahoraga... adapt.",
      "Chimera Shadow Garden!",
      "I'm not Gojo Satoru.",
      "I'll save people... even if I have to get my hands dirty."
    ],
    nobara: [
      "I love myself!",
      "A girl has to be selfish to survive.",
      "Resonance!",
      "I'll show you what a woman from the countryside can do!",
      "Don't look down on me!",
      "I'm Nobara Kugisaki!",
      "Straw Doll Technique!"
    ],
    sukuna: [
      "Know your place, insect.",
      "Stand proud. You are strong.",
      "Domain Expansion — Malevolent Shrine.",
      "Open.",
      "I alone am the honored one.",
      "How refreshing.",
      "A curse is a curse... but I'll play along."
    ],
    nanami: [
      "Overtime.",
      "I am a rational adult.",
      "Ratio Technique — seven to three.",
      "I'll finish this efficiently.",
      "Work is hard... but this is worse.",
      "After I die... please don't overwork.",
      "Expand."
    ],
    todo: [
      "Are you my type?!",
      "My best friend!",
      "Boogie Woogie!",
      "Black Flash, brother!",
      "Takada-chan!",
      "Simple is best!",
      "Our friendship is eternal!"
    ],
    maki: [
      "I don't need cursed energy.",
      "Heavenly Restriction.",
      "I'll cut through anything.",
      "Tools are enough.",
      "The Zenin clan ends with me.",
      "I'm free now.",
      "Watch closely."
    ],
    yuta: [
      "Rika!",
      "Don't touch my friends!",
      "I'll protect everyone.",
      "Copy...",
      "I'm the next Gojo Satoru? Don't be ridiculous.",
      "Domain Expansion — Authentic Mutual Love.",
      "I won't forgive you."
    ],
    mahito: [
      "The soul exists before the body!",
      "Idle Transfiguration!",
      "You're so interesting!",
      "Humans are so ugly... and so fun.",
      "Domain Expansion — Self-Embodiment of Perfection.",
      "I am a curse... and this is my nature.",
      "Touching the soul feels good."
    ],
    toji: [
      "I don't need cursed energy.",
      "A monkey like me...",
      "Heavenly Restriction — peak of physicality.",
      "You're coming with me.",
      "Kids these days...",
      "I sold my son for money. What a world.",
      "Sorry... Megumi."
    ],
    hakari: [
      "Jackpot!",
      "Idle Death Gamble!",
      "I'm gonna keep rolling!",
      "Infinite cursed energy!",
      "Probability is on my side.",
      "This is my domain!",
      "Don't stop the music!"
    ],
    choso: [
      "For my brothers!",
      "Blood Manipulation!",
      "Supernova!",
      "Yuji... you are my brother.",
      "I will protect my family.",
      "Convergence.",
      "We are the Death Paintings."
    ],
    jogo: [
      "Don't look down on me!",
      "Maximum Meteor!",
      "You humans are the real curse!",
      "Disaster Flames!",
      "Domain Expansion — Coffin of the Iron Mountain.",
      "Sukuna... acknowledge me!",
      "I am a disaster!"
    ],
    hanami: [
      "For the earth...",
      "Cursed Bud will bloom.",
      "Roots will bind you.",
      "Flower...",
      "Humans destroy nature.",
      "We are the true form of fear.",
      "Sleep within the forest."
    ],
    dagon: [
      "Death Swarm!",
      "Domain Expansion — Horizon of the Captivating Skandha.",
      "This is my ocean!",
      "Drown.",
      "I have matured!",
      "Endless fish...",
      "You will sink here."
    ],
    kenjaku: [
      "How interesting.",
      "The plan is proceeding smoothly.",
      "This body is quite useful.",
      "Uzumaki.",
      "Domain Expansion — Womb Profusion.",
      "Cursed spirits... humans... all pieces on the board.",
      "I've waited a thousand years for this."
    ],
    naoya: [
      "You are inferior.",
      "24 frames per second.",
      "Projection Sorcery.",
      "Domain Expansion — Time Cell Moon Palace.",
      "A woman? Don't make me laugh.",
      "I am the strongest Zenin!",
      "Frame by frame... you're already dead."
    ],
    uraume: [
      "For Lord Sukuna.",
      "Ice Formation.",
      "Know your place.",
      "Freeze.",
      "Lord Sukuna does not need you.",
      "Frost Calm.",
      "I have served for a thousand years."
    ],
    ryu: [
      "That was satisfying!",
      "Granite Blast!",
      "More! Give me a better fight!",
      "Maximum output!",
      "Cursed energy discharge!",
      "I only want a good battle.",
      "Don't disappoint me."
    ],
    uro: [
      "Sky Manipulation.",
      "Thin Ice Breaker!",
      "Don't mock the Fujiwara!",
      "The sky is my surface.",
      "I was treated as a tool...",
      "This grudge never fades.",
      "Fall from the sky."
    ],
    meimei: [
      "That'll cost you extra.",
      "Bird Strike.",
      "I don't work for free.",
      "Money talks.",
      "Ui Ui, handle it.",
      "Axe.",
      "Business is business."
    ],
    angel: [
      "Technique Extinguishment.",
      "Jacob's Ladder!",
      "In the name of the angel...",
      "Be purified.",
      "Your technique ends here.",
      "Hana... stay strong.",
      "Light of judgment!"
    ],
    geto: [
      "Are you the strongest because you're Gojo Satoru?",
      "Monkeys...",
      "I hate monkeys.",
      "The weak have no value.",
      "Riko... this world is wrong.",
      "Maximum: Uzumaki.",
      "We are not the same, Satoru."
    ],
    kashimo: [
      "Mythical Beast Amber!",
      "Lightning!",
      "I want a good fight!",
      "Discharge!",
      "One more satisfying battle...",
      "Staff of the remains.",
      "Electrify!"
    ],
    yuki: [
      "Mass... is everything.",
      "Star Rage!",
      "I want to create a world without cursed spirits.",
      "Garuda!",
      "Simple idea, right?",
      "Black hole...",
      "Don't underestimate a special grade."
    ],
    panda: [
      "I'm a panda!",
      "Gorilla mode!",
      "Core switch!",
      "Don't call me a stuffed animal!",
      "Tokyo Jujutsu High!",
      "Triple core!",
      "Let's go!"
    ],
    inumaki: [
      "Salmon!",
      "Don't move!",
      "Explode!",
      "Twist!",
      "Crush!",
      "Kelp...",
      "Mustard leaf!"
    ],
    shoko: [
      "Don't die on me.",
      "Reverse Cursed Technique.",
      "I need a smoke.",
      "Stay still.",
      "Another one...",
      "I'm a doctor, not a fighter.",
      "Gojo... Geto..."
    ],
    default: [
      "Haaah!",
      "Take this!",
      "Cursed energy!",
      "Not yet!",
      "Focus!",
      "Barrier up!",
      "Here I go!",
      "It's over!"
    ]
  },

  items: [
    { id: "coin", name: "Coins", type: "currency", desc: "Basic currency" },
    { id: "gem", name: "Gems", type: "currency", desc: "Premium currency" },
    { id: "xp_boost", name: "XP Boost", type: "consumable", desc: "Double XP for next training" },
    { id: "energy_potion", name: "Energy Potion", type: "consumable", desc: "Restore energy in battle" },
    { id: "upgrade_stone", name: "Upgrade Stone", type: "material", desc: "Used for character upgrades" },
    { id: "summon_ticket", name: "Summon Ticket", type: "summon", desc: "Free single summon" }
  ],

  ranks: ["E", "D", "C", "B", "A", "S", "SS", "SSS", "Special"],

  trainingTypes: [
    { id: "str", name: "Strength Training", stat: "atk", icon: "⚔️" },
    { id: "def", name: "Defense Training", stat: "def", icon: "🛡️" },
    { id: "spd", name: "Speed Training", stat: "spd", icon: "💨" },
    { id: "nrg", name: "Energy Training", stat: "energy", icon: "⚡" },
    { id: "tech", name: "Technique Training", stat: "xp", icon: "📜" }
  ]
};